from selenium.webdriver.common.by import By


class PipelineCreationLocator:
    NAME_INPUT = (By.XPATH, '//input[@type="text"]')
    DESCRIPTION_INPUT = (By.XPATH, '//textarea[@name="description"]')
    NEXT_BUTTON = (By.XPATH, '//*[@id="btn-create-job"]')
    ADD_NEW_INPUT_BUTTON = (By.XPATH, '//button[@id="btn-add-input"]')
    NAME_INPUT = (By.XPATH, '//input[@name="name"]')
    DATA_SET_SOURCE = (By.XPATH, '//input[@type="search"]')
    DATASET_SOURCE_OPTION = (By.XPATH, '//div[@role="option"]')
    ADD_INPUT_BUTTON = (By.XPATH, '//button[@id="btn-run-job"]')
    ADDED_INPUTS = (By.XPATH, '//div[@role="button"]')
    JOIN_BUTTON = (By.XPATH, '//button[@type="button"][3]')
    EDIT_JOINS_BUTTON = (By.XPATH, '//button[@id="types-input-btn"]')
    LEFT_DF_INPUT = (By.XPATH, '//input[@name="left_df"]')
    LEFT_ON_INPUT = (By.XPATH, '//input[@name="left_on"]')
    RIGHT_DF_INPUT = (By.XPATH, '//input[@name="right_df"]')
    RIGHT_ON_INPUT = (By.XPATH, '//input[@name="right_on"]')
    SAVE_JOIN_BUTTON = (By.XPATH, '//button[@type="submit"]')
    ADD_JOIN_BUTTON = (By.XPATH, '//button[@type="button" and @id="btn-run-job"]')
    JOINED_INPUTS_NODE = (By.XPATH, '//div[@role="button"][last()]')
    OUTPUT_BUTTON = (By.XPATH, '//button[@type="button"][5]')
    DATASET_NAME_INPUT = (By.XPATH, '//input[@name="dataset_name"]')
    ADD_OUTPUT_BUTTON = (By.XPATH, '//span[text()="Add Output"]')
    SAVE_PIPELINE_BUTTON = (By.XPATH, '//span[text()="Save Pipeline"]')
    TOASTER = (By.XPATH, '//div[@role="alert"]')